export const GOOGLE_MAPS_KEY = "AIzaSyDh1tbeXE_isu6eDL2c5P8HKdiI4kl2Ahc";
export const CLIENT_ID = "3CFNT3JETN3UXUPK2UK34ZFFEW1WEQXT1YWOSOLCESWCMC3Z";
export const CLIENT_SECRET = "3DZW2NJ4OVHWSXXYDYVA0KDHDNJEFAKECZ2YVN0HDVCMZBQ4";
